version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_LOG_RETENTION_HOURS=1
      - KAFKA_CFG_LOG_SEGMENT_BYTES=10485760
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_MESSAGE_MAX_BYTES=20971520
      - KAFKA_CFG_REPLICA_FETCH_MAX_BYTES=20971520
      - KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=20971520
      - KAFKA_CFG_TRANSACTION_TIMEOUT_MS=90000
      - KAFKA_CFG_REQUEST_TIMEOUT_MS=60000
      - KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS=3000
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092  # <-- ADD THIS
    depends_on:
      - zookeeper

